# Generated by Django 4.2.7 on 2025-11-03 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Метка')),
                ('x', models.FloatField(verbose_name='X координата')),
                ('y', models.FloatField(verbose_name='Y координата')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('height', models.FloatField(verbose_name='Высота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Аннотация',
                'verbose_name_plural': 'Аннотации',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название модели')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('model_type', models.CharField(choices=[('yolo', 'YOLO'), ('custom', 'Custom')], default='yolo', max_length=20, verbose_name='Тип модели')),
                ('status', models.CharField(choices=[('not_trained', 'Не обучена'), ('training', 'Обучается'), ('trained', 'Обучена'), ('error', 'Ошибка')], default='not_trained', max_length=20, verbose_name='Статус')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Точность')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='Precision')),
                ('recall', models.FloatField(blank=True, null=True, verbose_name='Recall')),
                ('f1_score', models.FloatField(blank=True, null=True, verbose_name='F1 Score')),
                ('epochs', models.IntegerField(default=50, verbose_name='Количество эпох')),
                ('batch_size', models.IntegerField(default=16, verbose_name='Размер батча')),
                ('img_size', models.IntegerField(default=640, verbose_name='Размер изображения')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/', verbose_name='Файл модели')),
                ('results_file', models.FileField(blank=True, null=True, upload_to='model_results/', verbose_name='Файл результатов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('trained_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обучения')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.dataset', verbose_name='Датасет')),
            ],
            options={
                'verbose_name': 'ML Модель',
                'verbose_name_plural': 'ML Модели',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_label', models.CharField(max_length=100, verbose_name='Обнаруженная метка')),
                ('confidence', models.FloatField(verbose_name='Уверенность')),
                ('x', models.FloatField(verbose_name='X координата')),
                ('y', models.FloatField(verbose_name='Y координата')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('height', models.FloatField(verbose_name='Высота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обнаружения')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.dataset', verbose_name='Датасет')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.imagefile', verbose_name='Изображение')),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.mlmodel', verbose_name='ML Модель')),
            ],
            options={
                'verbose_name': 'Результат детекции',
                'verbose_name_plural': 'Результаты детекции',
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('current_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataset.imagefile', verbose_name='Текущее изображение')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.dataset', verbose_name='Датасет')),
            ],
            options={
                'verbose_name': 'Сессия разметки',
                'verbose_name_plural': 'Сессии разметки',
            },
        ),
    ]
