# Generated by Django 4.2.7 on 2025-11-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачи Celery'),
        ),
    ]
