# Generated by Django 4.2.7 on 2025-11-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_mlmodel_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='training_log',
            field=models.TextField(blank=True, null=True, verbose_name='Лог обучения'),
        ),
    ]
