# Generated by Django 4.2.7 on 2025-11-03 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название отчета')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name='Формат')),
                ('total_images', models.IntegerField(verbose_name='Всего изображений')),
                ('annotated_images', models.IntegerField(verbose_name='Размеченных изображений')),
                ('total_annotations', models.IntegerField(verbose_name='Всего аннотаций')),
                ('total_detections', models.IntegerField(verbose_name='Всего обнаружений')),
                ('accuracy', models.FloatField(verbose_name='Точность')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='Точность (Precision)')),
                ('recall', models.FloatField(blank=True, null=True, verbose_name='Полнота (Recall)')),
                ('f1_score', models.FloatField(blank=True, null=True, verbose_name='F1-мера')),
                ('report_file', models.FileField(upload_to='reports/', verbose_name='Файл отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.dataset', verbose_name='Датасет')),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.mlmodel', verbose_name='ML Модель')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок раздела')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Раздел отчета',
                'verbose_name_plural': 'Разделы отчетов',
                'ordering': ['order'],
            },
        ),
    ]
