# Generated by Django 4.2.7 on 2025-11-05 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_initial'),
        ('dataset', '0002_initial'),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(verbose_name='Уверенность')),
                ('label', models.CharField(max_length=255, verbose_name='Метка')),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.detectionresult', verbose_name='Обнаружение')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.imagefile', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение отчета',
                'verbose_name_plural': 'Изображения отчетов',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='high_confidence_detections',
            field=models.IntegerField(default=0, verbose_name='Обнаружений с уверенностью >75%'),
        ),
        migrations.AddField(
            model_name='report',
            name='images_archive',
            field=models.FileField(blank=True, null=True, upload_to='reports/archives/', verbose_name='Архив с изображениями'),
        ),
        migrations.AddField(
            model_name='report',
            name='training_batch_size',
            field=models.IntegerField(default=0, verbose_name='Размер батча'),
        ),
        migrations.AddField(
            model_name='report',
            name='training_epochs',
            field=models.IntegerField(default=0, verbose_name='Количество эпох'),
        ),
        migrations.AddField(
            model_name='report',
            name='training_img_size',
            field=models.IntegerField(default=640, verbose_name='Размер изображения при обучении'),
        ),
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='Формат'),
        ),
        migrations.DeleteModel(
            name='ReportSection',
        ),
        migrations.AddField(
            model_name='reportimage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report', verbose_name='Отчет'),
        ),
    ]
